=== PvtVoid/flesh-and-blood-cards/json-schema/keyword-schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "unique_id": {
                "type": "string"
            },
            "name": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "description_plain": {
                "type": "string"
            }
        },
        "required": [
            "unique_id",
            "name",
            "description",
            "description_plain"
        ]
    }
}

=== PvtVoid/flesh-and-blood-cards/json/french/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "name": "Blocage Arcane X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "name": "Attaque",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "name": "Usure de Guerre",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "name": "Lame Brisée",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "name": "Boostez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "name": "Combo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "name": "Écrasement",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "name": "Dominer",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "name": "Go again",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "name": "Intimidez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "name": "Légendaire",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "name": "Optez X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "name": "Rechargez",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "name": "Reprise",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "name": "Spécialisation",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "name": "Temper",
        "description": "",
        "description_plain": ""
    }
]

=== PvtVoid/flesh-and-blood-cards/json/german/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "name": "Arkane Barriere X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "name": "Attacke",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "name": "Von der Schlacht gezeichnet",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "name": "Klingenbruch",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "name": "Boost",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "name": "Kombo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "name": "Zerschmetterung",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "name": "Dominieren",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "name": "Go again",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "name": "Einschüchtern",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "name": "Legendär",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "name": "Sortiere X Um",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "name": "Nachladen",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "name": "Fortführen",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "name": "Spezialisierung",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "name": "Tempern",
        "description": "",
        "description_plain": ""
    }
]

=== PvtVoid/flesh-and-blood-cards/json/spanish/keyword.json
[
    {
        "unique_id": "77JKJwz6k8BRrGbmRDPTT",
        "name": "Barrera arcana 2",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "tHNMT9DMtgRNTBrnCjdWq",
        "name": "Atacar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bKgtwKPTzJ69QdFDfm9bR",
        "name": "Desgaste de batalla",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cG88qzrJhwLnJH6TJ9cpp",
        "name": "Rotura de espada",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "wPWTbtBBwWkLhTz7hMrn7",
        "name": "Potenciar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "H6nNm6Nndrp8qTGFJL7GB",
        "name": "Combo",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "rG7F9GkDcmwNMczRbtwhL",
        "name": "Aplastar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "LdpzkhTrrcHJJtLFnctGW",
        "name": "Dominar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "mmf6BdTtrbCGrhdhg8K9g",
        "name": "Continuar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "NdTgddPBhJLhG7HRjqPG6",
        "name": "Intimidar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "TrD8trBHtDqmdKtd9jMWr",
        "name": "Legendario",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "bfRPRwTzzCPNRmNbfhdq7",
        "name": "Opta X",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "CMkCBFwkdRTkckLfBwhjL",
        "name": "Recargar",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "BN9pfqWtQjNgCHFrgmNHJ",
        "name": "Vuelta",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "cjn8CBRWPmdG8fwJNTBJt",
        "name": "Especialización",
        "description": "",
        "description_plain": ""
    },
    {
        "unique_id": "RnrzPrG6KfnCPhDCF8bpB",
        "name": "Carácter",
        "description": "",
        "description_plain": ""
    }
]
